"use strict";
// Auto-generated section of The Game Plan — see The Game Plan v2.html for original.
var { useState, useEffect, useRef } = React;
// ─── OVERFLOW MENU ───────────────────────────────────────────────────────────
function OverflowMenu({ dadName, partnerName, onSaveNames, onReviewOnboarding, onResetBirth, onResetBag, onResetAll, onClose }) {
    const [expanded, setExpanded] = useState(null);
    const [dadDraft, setDadDraft] = useState(dadName);
    const [partnerDraft, setPartnerDraft] = useState(partnerName);
    const toggle = (key) => setExpanded((e) => e === key ? null : key);
    function OvfIcon({ children, bg, color }) {
        return React.createElement("div", { className: "ovf-icon", style: { background: bg, color: color } }, children);
    }
    function Chevron({ k }) {
        return React.createElement("div", { className: `ovf-chevron ${expanded === k ? 'open' : ''}` },
            React.createElement("svg", { width: "14", height: "14", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" },
                React.createElement("polyline", { points: "9 18 15 12 9 6" })));
    }
    return (React.createElement(React.Fragment, null,
        React.createElement("div", { className: "ovf-scrim", onClick: onClose }),
        React.createElement("div", { className: "ovf-sheet" },
            React.createElement("div", { className: "ovf-handle" },
                React.createElement("div", { className: "ovf-drag" })),
            React.createElement("div", { className: "ovf-header" },
                React.createElement("div", null,
                    React.createElement("div", { className: "ovf-title" }, "Settings"),
                    React.createElement("div", { className: "ovf-names" },
                        dadName,
                        partnerName ? ` & ${partnerName}` : '')),
                React.createElement("button", { className: "ovf-close", onClick: onClose },
                    React.createElement("svg", { width: "12", height: "12", viewBox: "0 0 24 24", fill: "none", stroke: "var(--mid)", strokeWidth: "2.5", strokeLinecap: "round" },
                        React.createElement("line", { x1: "18", y1: "6", x2: "6", y2: "18" }),
                        React.createElement("line", { x1: "6", y1: "6", x2: "18", y2: "18" })))),
            React.createElement("div", { className: "ovf-divider" }),
            React.createElement("div", { className: "ovf-item", onClick: () => toggle('names') },
                React.createElement(OvfIcon, { bg: "var(--sage-bg)", color: "var(--sage)" },
                    React.createElement("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" },
                        React.createElement("path", { d: "M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7" }),
                        React.createElement("path", { d: "M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z" }))),
                React.createElement("div", { className: "ovf-item-text" },
                    React.createElement("div", { className: "ovf-item-label" }, "Edit names"),
                    React.createElement("div", { className: "ovf-item-sub" }, "Change how we address you two")),
                React.createElement(Chevron, { k: "names" })),
            expanded === 'names' &&
                React.createElement("div", { className: "ovf-expansion" },
                    React.createElement("div", { className: "ovf-exp-lbl" }, "Your name"),
                    React.createElement("input", { className: "ovf-exp-input", value: dadDraft, onChange: (e) => setDadDraft(e.target.value), placeholder: "Your name" }),
                    React.createElement("div", { className: "ovf-exp-lbl" }, "Partner's name"),
                    React.createElement("input", { className: "ovf-exp-input partner", value: partnerDraft, onChange: (e) => setPartnerDraft(e.target.value), placeholder: "Partner's name" }),
                    React.createElement("button", { className: "ovf-exp-save", onClick: () => { onSaveNames(dadDraft.trim(), partnerDraft.trim()); setExpanded(null); } }, "Save names")),
            React.createElement("div", { className: "ovf-item", onClick: () => { onReviewOnboarding(); onClose(); } },
                React.createElement(OvfIcon, { bg: "var(--amber-bg)", color: "var(--amber)" },
                    React.createElement("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" },
                        React.createElement("circle", { cx: "12", cy: "12", r: "10" }),
                        React.createElement("polygon", { points: "16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76" }))),
                React.createElement("div", { className: "ovf-item-text" },
                    React.createElement("div", { className: "ovf-item-label" }, "Review onboarding"),
                    React.createElement("div", { className: "ovf-item-sub" }, "Replay the welcome walkthrough")),
                React.createElement("div", { className: "ovf-chevron", style: { transform: 'rotate(-45deg)' } },
                    React.createElement("svg", { width: "14", height: "14", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" },
                        React.createElement("polyline", { points: "9 18 15 12 9 6" })))),
            React.createElement("div", { className: "ovf-item", onClick: () => toggle('export') },
                React.createElement(OvfIcon, { bg: "oklch(93% 0.04 220)", color: "oklch(42% 0.08 220)" },
                    React.createElement("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" },
                        React.createElement("path", { d: "M4 12v8a2 2 0 002 2h12a2 2 0 002-2v-8" }),
                        React.createElement("polyline", { points: "16 6 12 2 8 6" }),
                        React.createElement("line", { x1: "12", y1: "2", x2: "12", y2: "15" }))),
                React.createElement("div", { className: "ovf-item-text" },
                    React.createElement("div", { className: "ovf-item-label" }, "Export / Share"),
                    React.createElement("div", { className: "ovf-item-sub" }, "Copy your plan as text")),
                React.createElement(Chevron, { k: "export" })),
            expanded === 'export' &&
                React.createElement("div", { className: "ovf-export-placeholder" },
                    React.createElement("div", null,
                        React.createElement("div", { style: { fontSize: 13, fontWeight: 500, color: 'var(--navy)', marginBottom: 3 } }, "Coming soon"),
                        React.createElement("div", { style: { fontSize: 11, color: 'var(--soft)' } }, "PDF export and share link will be available in a future update.")),
                    React.createElement("div", { className: "ovf-soon-badge" }, "Soon")),
            React.createElement("div", { className: "ovf-divider", style: { margin: '4px 22px' } }),
            React.createElement("div", { className: "ovf-item", onClick: () => toggle('reset-birth') },
                React.createElement(OvfIcon, { bg: "var(--sage-bg)", color: "var(--sage)" },
                    React.createElement("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" },
                        React.createElement("polyline", { points: "1 4 1 10 7 10" }),
                        React.createElement("path", { d: "M3.51 15a9 9 0 102.13-9.36L1 10" }))),
                React.createElement("div", { className: "ovf-item-text" },
                    React.createElement("div", { className: "ovf-item-label" }, "Reset Birth Plan"),
                    React.createElement("div", { className: "ovf-item-sub" }, "Clear all birth plan answers")),
                React.createElement(Chevron, { k: "reset-birth" })),
            expanded === 'reset-birth' &&
                React.createElement("div", { className: "ovf-confirm" },
                    React.createElement("div", { className: "ovf-confirm-text" }, "This will clear all birth plan answers. Your bag selections are unaffected."),
                    React.createElement("div", { className: "ovf-confirm-btns" },
                        React.createElement("button", { className: "ovf-confirm-cancel", onClick: () => setExpanded(null) }, "Cancel"),
                        React.createElement("button", { className: "ovf-confirm-go", onClick: () => { onResetBirth(); setExpanded(null); onClose(); } }, "Clear plan"))),
            React.createElement("div", { className: "ovf-item", onClick: () => toggle('reset-bag') },
                React.createElement(OvfIcon, { bg: "var(--terra-bg)", color: "var(--terra)" },
                    React.createElement("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" },
                        React.createElement("path", { d: "M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z" }),
                        React.createElement("line", { x1: "3", y1: "6", x2: "21", y2: "6" }),
                        React.createElement("path", { d: "M16 10a4 4 0 01-8 0" }))),
                React.createElement("div", { className: "ovf-item-text" },
                    React.createElement("div", { className: "ovf-item-label" }, "Reset Labor Bag"),
                    React.createElement("div", { className: "ovf-item-sub" }, "Clear all bag selections")),
                React.createElement(Chevron, { k: "reset-bag" })),
            expanded === 'reset-bag' &&
                React.createElement("div", { className: "ovf-confirm" },
                    React.createElement("div", { className: "ovf-confirm-text" }, "This will clear all bag selections and packed items. Your birth plan is unaffected."),
                    React.createElement("div", { className: "ovf-confirm-btns" },
                        React.createElement("button", { className: "ovf-confirm-cancel", onClick: () => setExpanded(null) }, "Cancel"),
                        React.createElement("button", { className: "ovf-confirm-go", onClick: () => { onResetBag(); setExpanded(null); onClose(); } }, "Clear bag"))),
            React.createElement("div", { className: "ovf-item", onClick: () => toggle('reset-all') },
                React.createElement(OvfIcon, { bg: "oklch(95% 0.04 20)", color: "oklch(52% 0.15 20)" },
                    React.createElement("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" },
                        React.createElement("polyline", { points: "3 6 5 6 21 6" }),
                        React.createElement("path", { d: "M19 6l-1 14a2 2 0 01-2 2H8a2 2 0 01-2-2L5 6" }),
                        React.createElement("path", { d: "M10 11v6M14 11v6M9 6V4a1 1 0 011-1h4a1 1 0 011 1v2" }))),
                React.createElement("div", { className: "ovf-item-text" },
                    React.createElement("div", { className: "ovf-item-label dest" }, "Start over"),
                    React.createElement("div", { className: "ovf-item-sub" }, "Clear everything and restart")),
                React.createElement("div", { className: `ovf-chevron ${expanded === 'reset-all' ? 'open' : ''}`, style: { color: 'oklch(52% 0.15 20)', opacity: 0.6 } },
                    React.createElement("svg", { width: "14", height: "14", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" },
                        React.createElement("polyline", { points: "9 18 15 12 9 6" })))),
            expanded === 'reset-all' &&
                React.createElement("div", { className: "ovf-confirm" },
                    React.createElement("div", { className: "ovf-confirm-text" }, "This will clear all answers, bag selections, and your names. Everything starts fresh."),
                    React.createElement("div", { className: "ovf-confirm-btns" },
                        React.createElement("button", { className: "ovf-confirm-cancel", onClick: () => setExpanded(null) }, "Cancel"),
                        React.createElement("button", { className: "ovf-confirm-go", onClick: () => { onResetAll(); onClose(); } }, "Start over"))))));
}
// ─── HOME ────────────────────────────────────────────────────────────────────
function Home({ bAnswers, bagIncluded, bagCustom, bagPacked, bagInterviewDone, dadName, partnerName, onStart, onReset, onOpenOverflow }) {
    const allBagItems = [
        ...BAG_CATS.flatMap((c) => c.items.filter((i) => bagIncluded[i.id] !== false)),
        ...Object.values(bagCustom).flat()
    ];
    const bagTotal = allBagItems.length;
    const bagDone = allBagItems.filter((i) => bagPacked[i.id]).length;
    const birthDone = BPQ.filter((q) => { const a = getAns(bAnswers, q.id); return a.selected.length > 0 || a.custom; }).length;
    const birthFlagged = BPQ.filter((q) => getAns(bAnswers, q.id).flagged).length;
    return (React.createElement("div", { className: "screen" },
        React.createElement("div", { className: "scroll" },
            React.createElement("div", { className: "home-hero" },
                React.createElement("div", { style: { flex: 1, minWidth: 0 } },
                    React.createElement("div", { className: "eyebrow" }, dadName ? `Hey, ${dadName}` : 'Welcome, Dad'),
                    React.createElement("div", { className: "hero-title" }, "The Game Plan"),
                    React.createElement("div", { className: "hero-sub" }, partnerName ? `Prepare together with ${partnerName}.` : 'Two guided conversations to prepare together before labor begins.')),
                React.createElement("button", { className: "overflow-btn", onClick: onOpenOverflow, "aria-label": "Settings" },
                    React.createElement("svg", { width: "18", height: "18", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round" },
                        React.createElement("circle", { cx: "12", cy: "5", r: "1.2", fill: "currentColor" }),
                        React.createElement("circle", { cx: "12", cy: "12", r: "1.2", fill: "currentColor" }),
                        React.createElement("circle", { cx: "12", cy: "19", r: "1.2", fill: "currentColor" })))),
            React.createElement("div", { className: "prow" },
                React.createElement("button", { type: "button", className: "ppill", onClick: () => onStart(birthDone === BPQ.length ? "birth-summary" : "birth"), "aria-label": `Birth Plan, ${birthDone} of ${BPQ.length} topics` },
                    React.createElement("div", { className: "pring" },
                        React.createElement(PRing, { pct: birthDone / BPQ.length, color: "var(--sage)" }),
                        React.createElement("div", { className: "pring-lbl" }, birthDone === BPQ.length && React.createElement("span", { style: { color: "var(--sage)" } }, "\u2713"))),
                    React.createElement("div", null,
                        React.createElement("div", { className: "pinfo-name" }, "Birth Plan"),
                        React.createElement("div", { className: "pinfo-val" },
                            birthDone,
                            "/",
                            BPQ.length,
                            " topics"))),
                React.createElement("button", { type: "button", className: "ppill", onClick: () => onStart(bagInterviewDone ? "bag-summary" : "bag"), "aria-label": `Labor Bag, ${bagDone} of ${bagTotal} packed` },
                    React.createElement("div", { className: "pring" },
                        React.createElement(PRing, { pct: bagTotal ? bagDone / bagTotal : 0, color: "var(--terra)" }),
                        React.createElement("div", { className: "pring-lbl" }, bagTotal && bagDone === bagTotal && React.createElement("span", { style: { color: "var(--terra)" } }, "\u2713"))),
                    React.createElement("div", null,
                        React.createElement("div", { className: "pinfo-name" }, "Labor Bag"),
                        React.createElement("div", { className: "pinfo-val" },
                            bagDone,
                            "/",
                            bagTotal,
                            " packed")))),
            React.createElement("div", { style: { height: 4 } }),
            (birthDone === BPQ.length || bagInterviewDone) &&
                React.createElement(React.Fragment, null,
                    React.createElement("div", { className: "sec-lbl" }, "The Game Plan"),
                    React.createElement("div", { className: "cards", style: { marginBottom: 4 } },
                        birthDone === BPQ.length &&
                            React.createElement("div", { className: "hcard", onClick: () => onStart("birth-summary"), style: { borderLeft: "4px solid var(--sage)", borderRadius: "0 22px 22px 0" } },
                                React.createElement("div", { style: { display: "flex", alignItems: "center", gap: 12 } },
                                    React.createElement("div", { style: { width: 40, height: 40, borderRadius: 13, background: "var(--sage-bg)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, flexShrink: 0 } }, "\uD83C\uDFE5"),
                                    React.createElement("div", { style: { flex: 1 } },
                                        React.createElement("div", { className: "hcard-pre", style: { marginBottom: 2 } }, "Birth Plan"),
                                        React.createElement("div", { style: { fontFamily: "Lora, serif", fontSize: 17, fontWeight: 600, color: "var(--navy)" } }, "View our plan \u2192")),
                                    React.createElement("div", { style: { width: 32, height: 32, borderRadius: "50%", background: "var(--sage)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 } },
                                        React.createElement("svg", { width: "11", height: "9", viewBox: "0 0 10 8", fill: "none" },
                                            React.createElement("path", { d: "M1 4L3.5 6.5L9 1", stroke: "white", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }))))),
                        bagInterviewDone &&
                            React.createElement("div", { className: "hcard", onClick: () => onStart("bag-summary"), style: { borderLeft: "4px solid var(--terra)", borderRadius: "0 22px 22px 0" } },
                                React.createElement("div", { style: { display: "flex", alignItems: "center", gap: 12 } },
                                    React.createElement("div", { style: { width: 40, height: 40, borderRadius: 13, background: "var(--terra-bg)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, flexShrink: 0 } }, "\uD83C\uDF92"),
                                    React.createElement("div", { style: { flex: 1 } },
                                        React.createElement("div", { className: "hcard-pre", style: { marginBottom: 2 } }, "Labor Bag"),
                                        React.createElement("div", { style: { fontFamily: "Lora, serif", fontSize: 17, fontWeight: 600, color: "var(--navy)" } }, "View our bag list \u2192")),
                                    React.createElement("div", { style: { width: 32, height: 32, borderRadius: "50%", background: "var(--terra)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 } },
                                        React.createElement("svg", { width: "11", height: "9", viewBox: "0 0 10 8", fill: "none" },
                                            React.createElement("path", { d: "M1 4L3.5 6.5L9 1", stroke: "white", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round" }))))))),
            React.createElement("div", { style: { height: 16 } }),
            React.createElement("div", { className: "sec-lbl" }, "Your Interviews"),
            React.createElement("div", { className: "cards" },
                React.createElement("div", { className: "hcard", onClick: () => onStart("birth"), style: { borderLeft: "4px solid var(--sage)", borderRadius: "0 22px 22px 0" } },
                    React.createElement("div", { className: "hcard-accent", style: { background: "var(--sage)" } }),
                    React.createElement("div", { className: "hcard-icon", style: { background: "var(--sage-bg)" } }, "\uD83C\uDFE5"),
                    React.createElement("div", { className: "hcard-pre" }, "What's our plan?"),
                    React.createElement("div", { className: "hcard-title" }, "Birth Plan Interview"),
                    React.createElement("div", { className: "hcard-sub" }, "Let's build our Birth Plan"),
                    React.createElement("div", { className: "hcard-desc" }, "Pain management, interventions, who's in the room, cord cutting, skin-to-skin and more \u2014 answered together."),
                    React.createElement("div", { className: "hcard-foot" },
                        React.createElement("div", { className: "hcard-meta" },
                            BPQ.length,
                            " topics",
                            birthFlagged > 0 ? ` · ${birthFlagged} flagged` : ""),
                        React.createElement("div", { className: "hcard-cta" }, birthDone === BPQ.length ? "Done ✓" : birthDone > 0 ? "Continue →" : "Start →"))),
                React.createElement("div", { className: "hcard", onClick: () => onStart("bag"), style: { borderLeft: "4px solid var(--terra)", borderRadius: "0 22px 22px 0" } },
                    React.createElement("div", { className: "hcard-accent", style: { background: "var(--terra)" } }),
                    React.createElement("div", { className: "hcard-icon", style: { background: "var(--terra-bg)" } }, "\uD83C\uDF92"),
                    React.createElement("div", { className: "hcard-pre" }, "What to bring?"),
                    React.createElement("div", { className: "hcard-title" }, "Labor Bag Interview"),
                    React.createElement("div", { className: "hcard-sub" }, "Checklist items for our Labor Bag"),
                    React.createElement("div", { className: "hcard-desc" }, "Review suggested items, remove what you don't need, add your own \u2014 then pack category by category."),
                    React.createElement("div", { className: "hcard-foot" },
                        React.createElement("div", { className: "hcard-meta" },
                            bagTotal,
                            " items selected \u00B7 6 categories"),
                        React.createElement("div", { className: "hcard-cta", style: { color: "var(--terra)" } }, bagInterviewDone ? "Done ✓" : bagDone > 0 ? "Continue →" : "Start →")))),
            React.createElement(ProTips, null))));
}
Object.assign(window, { Home, OverflowMenu });
